on:
  workflow_call:
    inputs:
      release_title:
        type: string
        required: true
      release_tag:
        type: string
        required: true
      artifact_pattern:
        type: string
        required: false
permissions:
  contents: write
jobs:
  main:
    runs-on: ubuntu-latest
    name: Deploy Artifacts
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          pattern: ${{ inputs.artifact_pattern }}
          merge-multiple: true
      - name: Deploy Artifacts
        uses: marvinpinto/action-automatic-releases@latest
        with:
          files: artifacts/*
          title: ${{ inputs.release_title }}
          automatic_release_tag: ${{ inputs.release_tag }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}