name: Deploy Artifacts
on:
  workflow_call:
    inputs:
      release-title:
        type: string
        required: true
      release-tag:
        type: string
        required: true
permissions:
  contents: write
jobs:
  main:
    runs-on: ubuntu-latest
    name: ${{ github.workflow }}
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true
      - name: Deploy Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          files: artifacts/*
          title: ${{ inputs.release-title }}
          automatic_release_tag: ${{ inputs.release-tag }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}